# Generated by Django 3.2.16 on 2023-01-19 19:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20230119_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pubish',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
