# Generated by Django 3.2.16 on 2023-01-19 19:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_pubish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pubish',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
