# Generated by Django 3.2.16 on 2023-01-19 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_pubish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pubish',
            field=models.DateField(blank=True, null=True),
        ),
    ]
