# Generated by Django 3.2.16 on 2023-01-24 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20230124_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredientimage',
            name='file_test',
        ),
    ]
